# Generated by Django 5.0.7 on 2024-08-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco_hora', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CampoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='campo_pictures/')),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='campos.campo')),
            ],
        ),
    ]
