# Generated by Django 5.0.7 on 2024-08-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='iluminacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campo',
            name='tipo_gramado',
            field=models.CharField(choices=[('natural', 'Natural'), ('sintetico', 'Sintético')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campo',
            name='vestiarios',
            field=models.BooleanField(default=False),
        ),
    ]
