# Generated by Django 5.0.7 on 2024-08-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0002_campo_iluminacao_campo_tipo_gramado_campo_vestiarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
