# Generated by Django 5.0.7 on 2024-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0003_alter_campo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='cidade',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
