# Generated by Django 5.0.7 on 2024-08-08 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0005_alter_campo_cidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campo',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campos.cidade'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='campos.estado'),
        ),
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together={('nome', 'estado')},
        ),
    ]
