# Generated by Django 5.0.7 on 2024-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0006_cidade_estado_alter_campo_cidade_cidade_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(choices=[('rj', 'sp')], max_length=100, unique=True),
        ),
    ]
