# Generated by Django 5.0.7 on 2024-08-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0007_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
