# Generated by Django 5.0.7 on 2024-08-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0008_alter_estado_nome'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cidade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.AlterField(
            model_name='campo',
            name='cidade',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
    ]
