# Generated by Django 5.0.7 on 2024-08-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos', '0010_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
